A = int(input("Dê um valor para A:"))
B = int(input("Dê um valor para B:"))

print(A, "e", B)
print("____________________")
print("Soma de A e B:", A + B)
print("Subtração de A e B:", A - B)
print("Multiplicação de A e B:", A * B)
print("Divisão de A por B:", A / B)
print("____________________")
print("Continha resolvida!")